create table funcionario(
	codigo numeric(6) NOT NULL DEFAUlT nextval('seq1funcionario'),
	nome varchar(100),
	funcao numeric(10),
	crm varchar(30),
	cpf varchar(30),
	rg varchar(25),
	dtNascimento date,
	email varchar(40),
	sexo varchar(15),
	endereco varchar(200),
	numero varchar(50),
	complemento varchar(50),
	bairro varchar(50),
	cep varchar(50),
	cidade varchar(50),
	uf varchar(2),
	usuario varchar(50),
	dtcadastro date,
	dtAtualizacao date,
	sala varchar(10),
	senha varchar(15),
	telefone varchar(20),
	sigla varchar(3),
	tentativas numeric(2),
	PRIMARY KEY (codigo)
)