create table paciente(
		 codigo numeric(6) NOT NULL,
           nome text,
           status text,
          email text,
        fumante boolean,
	 alcoolatra boolean,
		  ativo text,
	codConvenio numeric(6),
 ultimaConsulta date,
   dtNascimento date,
     dtCadastro date,
  dtAtualizacao date,
       telefone text,
             RG text,
            CPF text,
           sexo text,
       endereco text,
		 numero text,
	complemento text,
			CEP text,
		 bairro text,
		 cidade text,
			 UF text,
			obs text,
		  foto bytea,
tentativas varchar(2),
			PRIMARY KEY (codigo))