/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.altessmann.NewTelas;

/**
 *
 * @author EngComp
 */
public class ContaCaixaNew extends javax.swing.JFrame {

    /**
     * Creates new form ContaCaixaNew
     */
    public ContaCaixaNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jComboSelecionaTipoPesquisa = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextCodigo = new javax.swing.JTextField();
        LabelCodigo = new javax.swing.JLabel();
        jTextCodigo1 = new javax.swing.JTextField();
        LabelCodigo1 = new javax.swing.JLabel();
        jTextCodigo3 = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jTextCodigo4 = new javax.swing.JTextField();
        LabelCodigo5 = new javax.swing.JLabel();
        jTextCodigo5 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaObs = new javax.swing.JTextArea();
        LabelObservacao = new javax.swing.JLabel();
        LabelCodigo2 = new javax.swing.JLabel();
        jTextCodigo2 = new javax.swing.JTextField();
        jButtonNovo2 = new javax.swing.JButton();
        jTextCodigo6 = new javax.swing.JTextField();
        jButtonNovo1 = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonGravar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conta Contabil", "Agencia", "Codigo", "Digito", "Nome", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCliente.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente.setRowHeight(20);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(0).setMaxWidth(200);
            jTableCliente.getColumnModel().getColumn(1).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(1).setMaxWidth(200);
            jTableCliente.getColumnModel().getColumn(2).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(2).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setMinWidth(300);
            jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(300);
            jTableCliente.getColumnModel().getColumn(4).setMaxWidth(300);
            jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        jTextPesquisar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        jTextPesquisar.setText("Selecione uma das opções de pesquisa ...");
        jTextPesquisar.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPesquisar.setPreferredSize(new java.awt.Dimension(500, 25));
        jTextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PesquisarCli.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar Conta");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jComboSelecionaTipoPesquisa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco", "Código", "Gerente" }));
        jComboSelecionaTipoPesquisa.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jTabbedPane1.addTab("  Pesquisar Conta  ", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Conta Caixa  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        jTextCodigo.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        LabelCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelCodigo.setText("Contabil Conta:");

        jTextCodigo1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo1.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo1.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo1ActionPerformed(evt);
            }
        });

        LabelCodigo1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelCodigo1.setText("Nome:");

        jTextCodigo3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo3.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo3.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo3ActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jTextCodigo4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo4.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo4.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo4ActionPerformed(evt);
            }
        });

        LabelCodigo5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelCodigo5.setText("Código / Digito:");

        jTextCodigo5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo5.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo5.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo5ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setText("Tipo:");

        jComboBox12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });

        AreaObs.setColumns(1);
        AreaObs.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        AreaObs.setLineWrap(true);
        AreaObs.setRows(1);
        AreaObs.setPreferredSize(null);
        jScrollPane2.setViewportView(AreaObs);

        LabelObservacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelObservacao.setText("Descrição:");

        LabelCodigo2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelCodigo2.setText("Agencia Banco:");

        jTextCodigo2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo2.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo2ActionPerformed(evt);
            }
        });

        jButtonNovo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo2ActionPerformed(evt);
            }
        });

        jTextCodigo6.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo6.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo6.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(LabelObservacao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCodigo)
                            .addComponent(LabelCodigo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jButtonNovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCodigo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelCodigo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jTextCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNovo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCodigo1)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(LabelObservacao)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonNovo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo1.setText("Nova Conta Caixa");
        jButtonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo1ActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar24x24.png"))); // NOI18N
        jButtonEditar.setText("Editar Cadastro");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close24x24.png"))); // NOI18N
        jButtonExcluir.setText("Excluir Cadastro");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save24x24.png"))); // NOI18N
        jButtonGravar.setText("Salvar Cadastro");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonGravar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel24x24.png"))); // NOI18N
        jButtonGravar1.setText("Cancelar Cadastro");
        jButtonGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonNovo1)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonEditar)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonExcluir)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonGravar)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonGravar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jTabbedPane1.addTab("  Cadastro Conta  ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {           // adiciona as tabelas de acordo com a String selecionada no jComboBox
            //
            //            String terminal = jComboSelecionaTipoPesquisa.getSelectedItem() + ""; // transforma o jComboBox em uma String
            //            try {
                //                if (terminal.equals("Código")) {    // compara para ver se a String e o codigo
                    //                    if (!clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).isEmpty()) { //testa para ver se existem clientes com o cpodigo informado
                        //                        for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                            //                            model.addRow(new String[]{jTextPesquisar.getText() + "", clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getNome(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getLogradouro(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getT1(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getStatus()});
                            //                        }
                        //                    } else {
                        //                        JOptionPane.showMessageDialog(null, "Não existem clientes com o código " + jTextPesquisar.getText() + " cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                        //                    }
                    //                }
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
                //
                //            }
            //            if (terminal.equals("Nome")) {
                //                if (!clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getCodigo() + "", clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getNome(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getLogradouro(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getT1(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //                }
                //                //clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(0).getCodigo();
                //            }
            //            if (terminal.equals("RG")) {
                //                if (!clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").isEmpty()) {
                    //                    System.out.println(clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome());
                    //
                    //                    model.addRow(new String[]{clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getCodigo() + "", clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getLogradouro(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getT1(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getStatus()});
                    //
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o RG '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "");
                //            }
            //
            //            if (terminal.equals("CPF")) {
                //
                //                if (!clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getCodigo() + "", clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getNome(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getLogradouro(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getT1(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o CPF '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null);
                //            }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        //        this.getGrupo(Integer.parseInt(jTextCodigo.getText()));
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo1ActionPerformed

    private void jTextCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo3ActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        //        this.jButtonNovo.setEnabled(false);
        //        this.ativaCampo();
        //        this.limpaCampo();
        //        this.jButtonGravar.setEnabled(true);
        //        this.setNovoCodigo();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo4ActionPerformed

    private void jTextCodigo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo5ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jButtonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo1ActionPerformed
        //        this.jButtonNovo.setEnabled(false);
        //        this.ativaCampo();
        //        this.limpaCampo();
        //        this.jButtonGravar.setEnabled(true);
        //        this.setNovoCodigo();
    }//GEN-LAST:event_jButtonNovo1ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //        this.ativaCampo();
        //        this.jButtonGravar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        //        String terminal = this.jComboGrupo.getSelectedItem() + "";
        //        char[] a = terminal.toCharArray();
        //        int posicao = 0;
        //        for (int i = 0; i < terminal.length(); i++) {
            //            if (a[i] == '-') {
                //                posicao = i;
                //            }
            //        }
        //        int codigoGrupo = Integer.parseInt(terminal.substring(0, posicao));
        //        try {
            //            if (subGrupoDAO.ContaCod(Integer.parseInt(jTextCodigo.getText())) == 0) {
                //                subGrupoDAO.setSubGrupo(jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            } else {
                //                subGrupoDAO.atualizaSubGrupo(Integer.parseInt(jTextCodigo.getText()), jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            }
            //            this.desativaCampo();
            //            this.jButtonGravar.setEnabled(false);
            //            this.jButtonNovo.setEnabled(true);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravar1ActionPerformed

    private void jTextCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo2ActionPerformed

    private void jButtonNovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo2ActionPerformed

    private void jTextCodigo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaCaixaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaCaixaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaCaixaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaCaixaNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaCaixaNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaObs;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelCodigo1;
    private javax.swing.JLabel LabelCodigo2;
    private javax.swing.JLabel LabelCodigo5;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravar1;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonNovo1;
    private javax.swing.JButton jButtonNovo2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCodigo1;
    private javax.swing.JTextField jTextCodigo2;
    private javax.swing.JTextField jTextCodigo3;
    private javax.swing.JTextField jTextCodigo4;
    private javax.swing.JTextField jTextCodigo5;
    private javax.swing.JTextField jTextCodigo6;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
