/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.altessmann.NewTelas;

/**
 *
 * @author EngComp
 */
public class MovimentoCaixaBancoNew extends javax.swing.JFrame {

    /**
     * Creates new form MovimentoCaixaNew
     */
    public MovimentoCaixaBancoNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jComboSelecionaTipoPesquisa = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonGravar4 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextCodigo1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextCodigo2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextCodigo3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextCodigo4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextCodigo5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCliente2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operação", "Conta Caixa", "Pessoa", "Data Lançamento", "Data Pago/Recebido", "Histórico", "Valor", "Descrição Documento de Origem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCliente.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente.setRowHeight(20);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(1).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(1).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(2).setMinWidth(250);
            jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableCliente.getColumnModel().getColumn(2).setMaxWidth(250);
            jTableCliente.getColumnModel().getColumn(3).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
            jTableCliente.getColumnModel().getColumn(6).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        }

        jTextPesquisar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        jTextPesquisar.setText("Selecione uma das opções de pesquisa ...");
        jTextPesquisar.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPesquisar.setPreferredSize(new java.awt.Dimension(500, 25));
        jTextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PesquisarCli.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar Movimento");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jComboSelecionaTipoPesquisa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Periodo", "ContaCaixa", "Situação" }));
        jComboSelecionaTipoPesquisa.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("  Pesquisar Movimento  ", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Detalhamento Movimento Caixa Banco  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Período:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Conta Caixa:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("CC MOVIMENTACAO BB");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("01/2016");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonGravar4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jButtonGravar4.setText("Gerar Fechamento");
        jButtonGravar4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar4ActionPerformed(evt);
            }
        });

        jButton29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonGravar4)
                .addGap(3, 3, 3)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonGravar4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Fechamento Movimento Caixa Banco   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Saldo Anterior:");

        jTextCodigo.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Recebimentos:");

        jTextCodigo1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo1.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo1.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Pagamentos:");

        jTextCodigo2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo2.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Saldo em Conta:");

        jTextCodigo3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo3.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo3.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Cheques Não Compensados:");

        jTextCodigo4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo4.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo4.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Saldo Disponivel:");

        jTextCodigo5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo5.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo5.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCodigo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        jTableCliente2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableCliente2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operação", "Conta Caixa", "Pessoa", "Data Lançamento", "Data Pago/Recebido", "Histórico", "Valor", "Descrição Documento de Origem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCliente2.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente2.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente2.setRowHeight(20);
        jTableCliente2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableCliente2);
        if (jTableCliente2.getColumnModel().getColumnCount() > 0) {
            jTableCliente2.getColumnModel().getColumn(0).setMinWidth(100);
            jTableCliente2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableCliente2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableCliente2.getColumnModel().getColumn(1).setMinWidth(150);
            jTableCliente2.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableCliente2.getColumnModel().getColumn(1).setMaxWidth(150);
            jTableCliente2.getColumnModel().getColumn(2).setMinWidth(250);
            jTableCliente2.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableCliente2.getColumnModel().getColumn(2).setMaxWidth(250);
            jTableCliente2.getColumnModel().getColumn(3).setMinWidth(150);
            jTableCliente2.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableCliente2.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableCliente2.getColumnModel().getColumn(4).setMinWidth(150);
            jTableCliente2.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableCliente2.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableCliente2.getColumnModel().getColumn(5).setMinWidth(200);
            jTableCliente2.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableCliente2.getColumnModel().getColumn(5).setMaxWidth(200);
            jTableCliente2.getColumnModel().getColumn(6).setMinWidth(100);
            jTableCliente2.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableCliente2.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableCliente2.getColumnModel().getColumn(7).setMinWidth(200);
            jTableCliente2.getColumnModel().getColumn(7).setPreferredWidth(200);
            jTableCliente2.getColumnModel().getColumn(7).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("  Movimento Detalhamento  ", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {           // adiciona as tabelas de acordo com a String selecionada no jComboBox
            //
            //            String terminal = jComboSelecionaTipoPesquisa.getSelectedItem() + ""; // transforma o jComboBox em uma String
            //            try {
                //                if (terminal.equals("Código")) {    // compara para ver se a String e o codigo
                    //                    if (!clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).isEmpty()) { //testa para ver se existem clientes com o cpodigo informado
                        //                        for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                            //                            model.addRow(new String[]{jTextPesquisar.getText() + "", clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getNome(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getLogradouro(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getT1(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getStatus()});
                            //                        }
                        //                    } else {
                        //                        JOptionPane.showMessageDialog(null, "Não existem clientes com o código " + jTextPesquisar.getText() + " cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                        //                    }
                    //                }
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
                //
                //            }
            //            if (terminal.equals("Nome")) {
                //                if (!clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getCodigo() + "", clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getNome(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getLogradouro(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getT1(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //                }
                //                //clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(0).getCodigo();
                //            }
            //            if (terminal.equals("RG")) {
                //                if (!clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").isEmpty()) {
                    //                    System.out.println(clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome());
                    //
                    //                    model.addRow(new String[]{clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getCodigo() + "", clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getLogradouro(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getT1(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getStatus()});
                    //
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o RG '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "");
                //            }
            //
            //            if (terminal.equals("CPF")) {
                //
                //                if (!clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getCodigo() + "", clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getNome(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getLogradouro(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getT1(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o CPF '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null);
                //            }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        //        this.getGrupo(Integer.parseInt(jTextCodigo.getText()));
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo1ActionPerformed

    private void jTextCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo2ActionPerformed

    private void jTextCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo3ActionPerformed

    private void jTextCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo4ActionPerformed

    private void jTextCodigo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo5ActionPerformed

    private void jButtonGravar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixaBancoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixaBancoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixaBancoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixaBancoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoCaixaBancoNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButtonGravar4;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableCliente2;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCodigo1;
    private javax.swing.JTextField jTextCodigo2;
    private javax.swing.JTextField jTextCodigo3;
    private javax.swing.JTextField jTextCodigo4;
    private javax.swing.JTextField jTextCodigo5;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
