/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.altessmann.NewTelas;

/**
 *
 * @author EngComp
 */
public class ParcelaPagamentoNew extends javax.swing.JFrame {

    /**
     * Creates new form ParcelaPagamentoNew
     */
    public ParcelaPagamentoNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboSelecionaTipoPesquisa = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonNovo1 = new javax.swing.JButton();
        jButtonGravar3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jTextCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();
        jButtonNovo2 = new javax.swing.JButton();
        jDateDtNascimento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jTextCodigo3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextCodigo4 = new javax.swing.JTextField();
        jTextCodigo5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboSelecionaTipoPesquisa1 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jTextDescricao2 = new javax.swing.JTextField();
        jTextCodigo8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButtonNovo4 = new javax.swing.JButton();
        jDateDtNascimento2 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jTextCodigo7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextCodigo9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextCodigo10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextCodigo11 = new javax.swing.JTextField();
        jTextCodigo12 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaObs = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selecionar", "Conta Caixa", "Fornecedor", "Nr Documento", "Status da Parcela", "Nr Parcela", "Data Emissão", "Data Vencimento", "Desconto Até", "Valor", "Taxa de Juro", "Taxa Multa", "Taxa Desconto", "Valor Juro", "Valor Multa", "Valor Desconto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCliente.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente.setRowHeight(20);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(1).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(2).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(3).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(3).setHeaderValue("Nr Documento");
            jTableCliente.getColumnModel().getColumn(4).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(4).setHeaderValue("Status da Parcela");
            jTableCliente.getColumnModel().getColumn(5).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(5).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(5).setHeaderValue("Nr Parcela");
            jTableCliente.getColumnModel().getColumn(6).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(6).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(6).setHeaderValue("Data Emissão");
            jTableCliente.getColumnModel().getColumn(7).setMinWidth(150);
            jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(7).setMaxWidth(150);
            jTableCliente.getColumnModel().getColumn(7).setHeaderValue("Data Vencimento");
            jTableCliente.getColumnModel().getColumn(8).setHeaderValue("Desconto Até");
            jTableCliente.getColumnModel().getColumn(9).setHeaderValue("Valor");
            jTableCliente.getColumnModel().getColumn(10).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(10).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(11).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(11).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(12).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(12).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(13).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(13).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(14).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(14).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(15).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(15).setMaxWidth(100);
        }

        jTextPesquisar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        jTextPesquisar.setText("Selecione uma das opções de pesquisa ...");
        jTextPesquisar.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPesquisar.setPreferredSize(new java.awt.Dimension(500, 25));
        jTextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PesquisarCli.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar Parcela");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrircli.png"))); // NOI18N
        jButton3.setText("Quitar Selecionadas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboSelecionaTipoPesquisa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "RG", "CPF" }));
        jComboSelecionaTipoPesquisa.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("  Pesquisar Parcelas  ", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Lançamentos a Pagar  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quitar.png"))); // NOI18N
        jButtonNovo1.setText("Efetuar Pagamento");
        jButtonNovo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo1ActionPerformed(evt);
            }
        });

        jButtonGravar3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel24x24.png"))); // NOI18N
        jButtonGravar3.setText("Cancelar");
        jButtonGravar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar3ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonNovo1)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGravar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextCodigo.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Tipo Pagamento:");

        jTextDescricao.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextDescricao.setForeground(new java.awt.Color(153, 153, 153));
        jTextDescricao.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricaoActionPerformed(evt);
            }
        });

        jButtonNovo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo2ActionPerformed(evt);
            }
        });

        jDateDtNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDateDtNascimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png")));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Data Vencimento:");

        jTextCodigo3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo3.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo3.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Taxa Desconto:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Valor a Pagar:");

        jTextCodigo4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo4.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo4.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo4ActionPerformed(evt);
            }
        });

        jTextCodigo5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo5.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo5.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Taxa Juro:");

        jComboSelecionaTipoPesquisa1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Total" }));
        jComboSelecionaTipoPesquisa1.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setText("Tipo Baixa:");

        jTextDescricao2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextDescricao2.setForeground(new java.awt.Color(153, 153, 153));
        jTextDescricao2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextDescricao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricao2ActionPerformed(evt);
            }
        });

        jTextCodigo8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo8.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo8.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo8ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setText("Conta Caixa:");

        jButtonNovo4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo4ActionPerformed(evt);
            }
        });

        jDateDtNascimento2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDateDtNascimento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png")));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Data Pagamento:");

        jTextCodigo7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo7.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo7.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo7ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("Valor Juro:");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setText("Taxa Multa:");

        jTextCodigo9.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo9.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo9.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo9ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("Valor Multa:");

        jTextCodigo10.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo10.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo10.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo10ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setText("Valor Desconto:");

        jTextCodigo11.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo11.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo11.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo11ActionPerformed(evt);
            }
        });

        jTextCodigo12.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextCodigo12.setForeground(new java.awt.Color(153, 153, 153));
        jTextCodigo12.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextCodigo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo12ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setText("Valor Pago:");

        AreaObs.setColumns(1);
        AreaObs.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        AreaObs.setLineWrap(true);
        AreaObs.setRows(1);
        AreaObs.setPreferredSize(null);
        jScrollPane3.setViewportView(AreaObs);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setText("Histórico:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23)
                                    .addComponent(jComboSelecionaTipoPesquisa1, 0, 160, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jButtonNovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jTextCodigo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addComponent(jButtonNovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jDateDtNascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTextCodigo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCodigo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCodigo7, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCodigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTextCodigo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCodigo11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jTextCodigo12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(1, 1, 1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboSelecionaTipoPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(1, 1, 1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextCodigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonNovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addComponent(jButtonNovo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(1, 1, 1)
                        .addComponent(jTextCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(1, 1, 1)
                        .addComponent(jDateDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(1, 1, 1)
                        .addComponent(jDateDtNascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(1, 1, 1)
                        .addComponent(jTextCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(1, 1, 1)
                        .addComponent(jTextCodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(1, 1, 1)
                                .addComponent(jTextCodigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(1, 1, 1)
                                .addComponent(jTextCodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(1, 1, 1)
                            .addComponent(jTextCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(1, 1, 1)
                        .addComponent(jTextCodigo12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(1, 1, 1)
                        .addComponent(jTextCodigo11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTableCliente1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr Cheque", "Tipo Pagamento", "Conta Caixa", "Data Pagamento", "Taxa de Juro", "Valor Juro", "Taxa Multa", "Valor Multa", "Taxa Desconto", "Valor Desconto", "Valor Pago", "Histórico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCliente1.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente1.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente1.setRowHeight(20);
        jTableCliente1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableCliente1);
        if (jTableCliente1.getColumnModel().getColumnCount() > 0) {
            jTableCliente1.getColumnModel().getColumn(0).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(1).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(2).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(3).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(4).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(5).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(5).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(6).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(7).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(7).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(8).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(8).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(9).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(9).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(10).setMinWidth(100);
            jTableCliente1.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTableCliente1.getColumnModel().getColumn(10).setMaxWidth(100);
            jTableCliente1.getColumnModel().getColumn(11).setMinWidth(200);
            jTableCliente1.getColumnModel().getColumn(11).setPreferredWidth(200);
            jTableCliente1.getColumnModel().getColumn(11).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(384, 384, 384)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("  Parcela Pagamento  ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {           // adiciona as tabelas de acordo com a String selecionada no jComboBox
            //
            //            String terminal = jComboSelecionaTipoPesquisa.getSelectedItem() + ""; // transforma o jComboBox em uma String
            //            try {
                //                if (terminal.equals("Código")) {    // compara para ver se a String e o codigo
                    //                    if (!clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).isEmpty()) { //testa para ver se existem clientes com o cpodigo informado
                        //                        for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                            //                            model.addRow(new String[]{jTextPesquisar.getText() + "", clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getNome(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getLogradouro(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getT1(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getStatus()});
                            //                        }
                        //                    } else {
                        //                        JOptionPane.showMessageDialog(null, "Não existem clientes com o código " + jTextPesquisar.getText() + " cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                        //                    }
                    //                }
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
                //
                //            }
            //            if (terminal.equals("Nome")) {
                //                if (!clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getCodigo() + "", clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getNome(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getLogradouro(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getT1(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //                }
                //                //clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(0).getCodigo();
                //            }
            //            if (terminal.equals("RG")) {
                //                if (!clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").isEmpty()) {
                    //                    System.out.println(clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome());
                    //
                    //                    model.addRow(new String[]{clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getCodigo() + "", clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getLogradouro(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getT1(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getStatus()});
                    //
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o RG '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "");
                //            }
            //
            //            if (terminal.equals("CPF")) {
                //
                //                if (!clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getCodigo() + "", clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getNome(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getLogradouro(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getT1(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o CPF '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null);
                //            }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {
            //            if (!clienteDAO.getCliente("", null, null).isEmpty()) {
                //                for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                    //                    model.addRow(new String[]{clienteDAO.getCliente().get(i).getCodigo() + "", clienteDAO.getCliente().get(i).getNome(), clienteDAO.getCliente().get(i).getLogradouro(), clienteDAO.getCliente().get(i).getT1(), clienteDAO.getCliente().get(i).getStatus()});
                    //                }
                //            } else {
                //                JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                //            }
            //        } catch (SQLException ex) {
            //            System.out.println(ex);
            //        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo1ActionPerformed

    private void jButtonGravar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravar3ActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        //        this.getGrupo(Integer.parseInt(jTextCodigo.getText()));
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricaoActionPerformed

    private void jButtonNovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo2ActionPerformed

    private void jTextCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo3ActionPerformed

    private void jTextCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo4ActionPerformed

    private void jTextCodigo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo5ActionPerformed

    private void jTextDescricao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricao2ActionPerformed

    private void jTextCodigo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo8ActionPerformed

    private void jButtonNovo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo4ActionPerformed

    private void jTextCodigo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo7ActionPerformed

    private void jTextCodigo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo9ActionPerformed

    private void jTextCodigo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo10ActionPerformed

    private void jTextCodigo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo11ActionPerformed

    private void jTextCodigo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcelaPagamentoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcelaPagamentoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcelaPagamentoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcelaPagamentoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParcelaPagamentoNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaObs;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonGravar3;
    private javax.swing.JButton jButtonNovo1;
    private javax.swing.JButton jButtonNovo2;
    private javax.swing.JButton jButtonNovo4;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa1;
    private com.toedter.calendar.JDateChooser jDateDtNascimento;
    private com.toedter.calendar.JDateChooser jDateDtNascimento2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableCliente1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCodigo10;
    private javax.swing.JTextField jTextCodigo11;
    private javax.swing.JTextField jTextCodigo12;
    private javax.swing.JTextField jTextCodigo3;
    private javax.swing.JTextField jTextCodigo4;
    private javax.swing.JTextField jTextCodigo5;
    private javax.swing.JTextField jTextCodigo7;
    private javax.swing.JTextField jTextCodigo8;
    private javax.swing.JTextField jTextCodigo9;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextDescricao2;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
